# Generated by Django 4.1.7 on 2023-04-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название зоны обслуживания.', max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание зоны обслуживания.', verbose_name='описание')),
                ('branch', models.ForeignKey(help_text='Филиал, к которому относится зона обслуживания.', on_delete=django.db.models.deletion.CASCADE, to='branch.branch', verbose_name='филиал')),
            ],
            options={
                'verbose_name': 'зона обслуживания',
                'verbose_name_plural': 'зоны обслуживания',
            },
        ),
    ]
