# Generated by Django 4.1.7 on 2023-04-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('service_zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='service_zone.servicezone', verbose_name='зоны обслуживания')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_zones', to='users.technician', verbose_name='техник')),
            ],
            options={
                'verbose_name': 'Зона техника',
                'verbose_name_plural': 'Зоны техников',
            },
        ),
        migrations.AddConstraint(
            model_name='technicianzone',
            constraint=models.UniqueConstraint(fields=('technician', 'service_zone'), name='unique_follow'),
        ),
    ]
