# Generated by Django 4.1.7 on 2023-04-11 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Укажите, активена ли учетная запись инженер', verbose_name='активен')),
                ('last_name', models.CharField(help_text='Фамилия инженера', max_length=30, verbose_name='фамилия')),
                ('first_name', models.CharField(help_text='Имя инженера', max_length=30, verbose_name='имя')),
                ('middle_name', models.CharField(help_text='Отчество инженера', max_length=30, verbose_name='отчество')),
                ('phone', models.CharField(help_text='Телефон инженера', max_length=20, verbose_name='телефон')),
                ('photo', models.ImageField(blank=True, help_text='Фото инженера', null=True, upload_to='engineer_photos', verbose_name='фото')),
                ('branch', models.ForeignKey(help_text='Выберите филиал, к которому относится инженер', on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='филиал')),
                ('user', models.OneToOneField(help_text='Пользователь, к которому относится инженер', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'инженер',
                'verbose_name_plural': 'инженеры',
            },
        ),
    ]
