# Generated by Django 4.1.7 on 2023-04-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Укажите, активена ли учетная запись инженер', verbose_name='активен'),
        ),
    ]
