# Generated by Django 4.1.7 on 2023-04-11 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Укажите, активена ли учетная запись', verbose_name='активен')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=30, verbose_name='имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=30, verbose_name='фамилия')),
                ('middle_name', models.CharField(blank=True, help_text='Введите отчество', max_length=30, verbose_name='отчество')),
                ('phone', models.CharField(blank=True, help_text='Введите телефон', max_length=20, verbose_name='телефон')),
                ('photo', models.ImageField(blank=True, help_text='Выберите фото', upload_to='technicians/photos/', verbose_name='фото')),
                ('branch', models.ForeignKey(help_text='Выберите филиал, к которому относится техник', on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='филиал')),
                ('user', models.OneToOneField(help_text='Пользователь, к которому относится', on_delete=django.db.models.deletion.CASCADE, related_name='technician', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'техник',
                'verbose_name_plural': 'техники',
            },
        ),
    ]
