# Generated by Django 4.1.7 on 2023-04-09 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(help_text='Пользователь, к которому относится', on_delete=django.db.models.deletion.CASCADE, related_name='technician', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
