# Generated by Django 4.1.7 on 2023-04-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_оrganizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorganizations',
            options={'verbose_name': 'Сервесная организация', 'verbose_name_plural': 'Сервисные организации'},
        ),
    ]
