# Generated by Django 4.1.7 on 2023-04-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('service_zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='FireAlarmObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название объекта, на котором установлена пожарная сигнализация.', max_length=255, verbose_name='название объекта')),
                ('frequency', models.CharField(choices=[('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально')], help_text='Периодичность обслуживания пожарной сигнализации на объекте.', max_length=10, verbose_name='периодичность обслуживания')),
                ('last_service_date', models.DateField(help_text='Дата последнего обслуживания пожарной сигнализации на объекте.', verbose_name='дата последнего обслуживания')),
                ('next_service_date', models.DateField(blank=True, help_text='Дата следующего обслуживания пожарной сигнализации на объекте.', null=True, verbose_name='дата следующего обслуживания')),
                ('photo', models.ImageField(blank=True, help_text='Фотография объекта, на котором установлена пожарная сигнализация.', null=True, upload_to='', verbose_name='фото объекта')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_alarm_objects', to='fire_alarm_objects.address', verbose_name='Адрес объекта')),
                ('branch', models.ForeignKey(help_text='Филиал, к которому относится данный объект.', on_delete=django.db.models.deletion.CASCADE, related_name='fire_alarm_objects', to='branches.branch', verbose_name='филиал')),
                ('service_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fire_alarm_objects', to='service_zones.servicezone', verbose_name='Зона обслуживания')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
            },
        ),
    ]
