# Generated by Django 4.1.7 on 2023-04-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('technicians', '0001_initial'),
        ('service_zones', '0001_initial'),
        ('service_оrganizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='FireAlarmObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название объекта, на котором установлена пожарная сигнализация.', max_length=255, verbose_name='название объекта')),
                ('frequency', models.CharField(choices=[('Ежемесячно', 'Ежемесячно'), ('Ежеквартально', 'Ежеквартально')], help_text='Периодичность обслуживания пожарной сигнализации на объекте.', max_length=15, verbose_name='периодичность обслуживания')),
                ('last_service_date', models.DateField(help_text='Дата последнего обслуживания пожарной сигнализации на объекте.', verbose_name='дата последнего обслуживания')),
                ('next_service_date', models.DateField(blank=True, help_text='Дата следующего обслуживания пожарной сигнализации на объекте.', null=True, verbose_name='дата следующего обслуживания')),
                ('photo', models.ImageField(blank=True, help_text='Фотография объекта, на котором установлена пожарная сигнализация.', null=True, upload_to='service_photos/', verbose_name='фото объекта')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_alarm_objects', to='fire_alarm_objects.address', verbose_name='Адрес объекта')),
                ('branch', models.ForeignKey(help_text='Филиал, к которому относится данный объект.', on_delete=django.db.models.deletion.CASCADE, related_name='fire_alarm_objects', to='branches.branch', verbose_name='филиал')),
                ('service_organizations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fire_alarm_objects', to='service_оrganizations.serviceorganizations', verbose_name='Обслуживающия организация')),
                ('service_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_alarm_objects', to='service_zones.servicezone', verbose_name='Зона обслуживания')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
            },
        ),
        migrations.CreateModel(
            name='FireAlarmObjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('service_journal_photo', models.ImageField(upload_to='service_photos/', verbose_name='Фотография журнала техобслуживания ПС')),
                ('control_panel_photo', models.ImageField(upload_to='service_photos/', verbose_name='Фотография головного прибора ПС')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('fire_alarm_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_done', to='fire_alarm_objects.firealarmobject', verbose_name='Объект')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_done', to='technicians.technician', verbose_name='Техник')),
            ],
            options={
                'verbose_name': 'Обслуживание объекта',
                'verbose_name_plural': 'Обслуживания объектов',
            },
        ),
        migrations.CreateModel(
            name='FailedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'Выполняется'), ('completed', 'Завершено')], default='pending', max_length=255)),
                ('service_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='failed_service_photos/', verbose_name='Фото неисправности')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('fire_alarm_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_services', to='fire_alarm_objects.firealarmobject')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failed_services', to='technicians.technician', verbose_name='Техник')),
            ],
        ),
    ]
