# Generated by Django 4.1.7 on 2023-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alarm_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealarmobject',
            name='remote_number',
            field=models.FloatField(blank=True, null=True, verbose_name='Пультовый номер'),
        ),
    ]
