# Generated by Django 4.1.7 on 2023-04-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alarm_objects', '0002_firealarmobject_remote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealarmobject',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Помещение'),
        ),
    ]
