# Generated by Django 4.1.7 on 2023-04-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_zones', '0001_initial'),
        ('fire_alarm_objects', '0002_firealarmobject_service_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firealarmobject',
            name='service_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_alarm_objects', to='service_zones.servicezone', verbose_name='Зона обслуживания'),
        ),
    ]
