# Generated by Django 4.1.7 on 2023-04-07 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
        ('fire_alarm_objects', '0003_alter_firealarmobject_service_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='failedservices/')),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireAlarmObjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('service_journal_photo', models.ImageField(upload_to='service_photos', verbose_name='Фотография журнала техобслуживания ПС')),
                ('control_panel_photo', models.ImageField(upload_to='service_photos', verbose_name='Фотография головного прибора ПС')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire_alarm_objects.firealarmobject', verbose_name='Объект')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technicians.technician', verbose_name='Техник')),
            ],
            options={
                'verbose_name': 'Обслуживание объекта',
                'verbose_name_plural': 'Обслуживания объектов',
            },
        ),
        migrations.CreateModel(
            name='FailedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'Выполняется'), ('completed', 'Завершено')], default='pending', max_length=255)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('failed_service_photos', models.ManyToManyField(to='fire_alarm_objects.failedservicephoto')),
                ('fire_alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire_alarm_objects.firealarmobject')),
            ],
        ),
    ]
