# Generated by Django 4.1.7 on 2023-04-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alarm_objects', '0004_failedservicephoto_firealarmobjectservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firealarmobjectservice',
            name='control_panel_photo',
            field=models.ImageField(upload_to='service_photos/', verbose_name='Фотография головного прибора ПС'),
        ),
        migrations.AlterField(
            model_name='firealarmobjectservice',
            name='service_journal_photo',
            field=models.ImageField(upload_to='service_photos/', verbose_name='Фотография журнала техобслуживания ПС'),
        ),
    ]
