# Generated by Django 4.1.7 on 2023-04-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alarm_objects', '0004_alter_firealarmobject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealarmobject',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заключения договора'),
        ),
        migrations.AddField(
            model_name='firealarmobject',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер договора'),
        ),
    ]
