# Generated by Django 4.1.7 on 2023-04-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alarm_objects', '0005_alter_firealarmobjectservice_control_panel_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firealarmobjectservice',
            old_name='object',
            new_name='fire_alarm_object',
        ),
    ]
