# Generated by Django 4.1.7 on 2023-04-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
        ('fire_alarm_objects', '0006_rename_object_firealarmobjectservice_fire_alarm_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firealarmobjectservice',
            name='fire_alarm_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_done', to='fire_alarm_objects.firealarmobject', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='firealarmobjectservice',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_done', to='technicians.technician', verbose_name='Техник'),
        ),
    ]
