# Generated by Django 4.1.7 on 2023-04-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alarm_objects', '0006_alter_failedservice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firealarmobject',
            name='remote_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пультовый номер'),
        ),
    ]
