# Generated by Django 4.1.7 on 2023-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alarm_objects', '0007_alter_firealarmobjectservice_fire_alarm_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firealarmobject',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фотография объекта, на котором установлена пожарная сигнализация.', null=True, upload_to='service_photos/', verbose_name='фото объекта'),
        ),
    ]
