# Generated by Django 4.1.7 on 2023-04-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alarm_objects', '0007_alter_firealarmobject_remote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealarmobjectservice',
            name='service_journal_title_page_photo',
            field=models.ImageField(blank=True, default='media/default_image.jpg', upload_to='service_photos/', verbose_name='Фотография обложки журнала техобслуживания ПС'),
        ),
    ]
