# Generated by Django 4.1.7 on 2023-04-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название зоны обслуживания.', max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание зоны обслуживания.', verbose_name='описание')),
                ('geopoints', models.TextField(help_text='Геоточки, образующие область зоны обслуживания.', verbose_name='геоточки')),
                ('branch', models.ForeignKey(help_text='Филиал, к которому относится зона обслуживания.', on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='филиал')),
            ],
            options={
                'verbose_name': 'зона обслуживания',
                'verbose_name_plural': 'зоны обслуживания',
            },
        ),
        migrations.CreateModel(
            name='TechnicianZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='service_zones.servicezone', verbose_name='зоны обслуживания')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_zones', to='technicians.technician', verbose_name='техник')),
            ],
            options={
                'verbose_name': 'Зона техника',
                'verbose_name_plural': 'Зоны техников',
            },
        ),
        migrations.AddConstraint(
            model_name='technicianzone',
            constraint=models.UniqueConstraint(fields=('technician', 'service_zone'), name='unique_follow'),
        ),
    ]
