# Generated by Django 4.1.7 on 2023-04-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicezone',
            name='color',
            field=models.CharField(default='#7df9ff33', help_text='Уникальный цвет зоны обслуживания.', max_length=10, unique=True, verbose_name='цвет'),
        ),
    ]
