# Generated by Django 4.1.7 on 2023-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_zones', '0002_servicezone_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicezone',
            name='color',
            field=models.CharField(help_text='Уникальный цвет зоны обслуживания.', max_length=10, verbose_name='цвет'),
        ),
    ]
