# Generated by Django 4.1.2 on 2022-11-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fire_safety_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_object', models.TextField()),
                ('address_object', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_service', models.DateField()),
                ('photo_report', models.ImageField(upload_to=None, verbose_name='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
