# Generated by Django 4.1.7 on 2023-04-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Введите название филиала', max_length=50, verbose_name='название')),
                ('longitude', models.FloatField(blank=True, help_text='Введите долготу филиала', null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(blank=True, help_text='Введите широту филиала', null=True, verbose_name='широта')),
            ],
            options={
                'verbose_name': 'филиал',
                'verbose_name_plural': 'филиалы',
            },
        ),
    ]
