# Generated by Django 4.1.7 on 2023-04-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_latitude_alter_branch_longitude'),
        ('branches', '0002_alter_branch_options_alter_branch_latitude_and_more'),
    ]

    operations = [
    ]
