# Generated by Django 4.1.7 on 2023-04-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_merge_20230430_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'филиал', 'verbose_name_plural': 'филиалы'},
        ),
    ]
